name: flutterflask
description: AMG | ABSH | P007
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  # config
  shared_preferences: 2.0.5
  # file_picker: ^2.1.7
  image_picker: ^0.7.4
  http: ^0.13.3
  # animations/effects
  simple_animations: ^1.3.11
  toast: ^0.1.5
  flutter_styled_toast: ^1.5.2+3
  bot_toast: ^4.0.1
  dio: ^4.0.0
  device_info_plus: ^1.0.1
  dart_ipify: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - resources/images/
    - resources/sounds/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
